[vlan20]
# srv-web non joignable
# srv-db non joignable

[vlan30]
# srv-wazuh non joignable
# srv-graylog non joignable

[vlan40]
# srv-ia non joignable

[all_vms:children]
vlan20
vlan30
vlan40

[all_vms:vars]
ansible_user=debian
ansible_ssh_private_key_file=/home/runner/.ssh/id_ed25519_isrc
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o BindAddress=192.168.50.21'
ansible_python_interpreter=/usr/bin/python3
