# ============================================================
#  Ansible Inventory — Projet ISRC LOGISTIA
#  srv-runner : ens18 (192.168.50.21) pour joindre les VMs
#  Toutes les VMs sont en Debian 12
# ============================================================

# ---- VLAN 20 — Serveurs web et base de données ----
[vlan20]
srv-web     ansible_host=192.168.20.10
srv-db      ansible_host=192.168.20.11

# ---- VLAN 30 — SOC et logs ----
[vlan30]
srv-wazuh   ansible_host=192.168.30.10
srv-graylog ansible_host=192.168.30.20

# ---- VLAN 40 — Intelligence artificielle ----
[vlan40]
srv-ia      ansible_host=192.168.40.10

# ---- Toutes les VMs ----
[all_vms:children]
vlan20
vlan30
vlan40

# ---- Variables communes à toutes les VMs ----
[all_vms:vars]
ansible_user=debian
ansible_ssh_private_key_file=/root/.ssh/id_ed25519_isrc
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o BindAddress=192.168.50.21'
ansible_python_interpreter=/usr/bin/python3
