[vlan20]
# SRV-VM-WEB non joignable
# SRV-VM-DB non joignable

[vlan30]
# SRV-VM-WAZUH non joignable
# SRV-VM-GRAYLOG non joignable

[vlan40]
# SRV-VM-IA non joignable

[all_vms:children]
vlan20
vlan30
vlan40

[all_vms:vars]
ansible_user=debian
ansible_ssh_private_key_file=/home/runner/.ssh/id_ed25519_isrc
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o BindAddress=192.168.50.21'
ansible_python_interpreter=/usr/bin/python3
